version: '3.4'

services:
  cnpchallenge.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      SQLCONNSTR_Default: Server=tcp:cnpchallenge.db,1433;Initial Catalog=app-production;User ID=SA;Password=@B7w84A9ZWtl;TrustServerCertificate=True;
      SQLCONNSTR_Testing: Server=tcp:cnpchallenge.db,1433;Initial Catalog=app-testing;User ID=SA;Password=@B7w84A9ZWtl;TrustServerCertificate=True;
    ports:
      - "7000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  cnpchallenge.db:
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "@B7w84A9ZWtl"
      ACCEPT_EULA: "Y"